DB_COLUMNS = [
    "license_plate",
    "brand",
    "commercial_name",
    "setup",
    "mass_empty",
    "mass_max",
    "mass_ready",
    "first_color",
    "second_color",
    "number_of_cilinders",
    "cilinder_size",
    "environmental_label",
    "catalog_prize",
    "length"
]


COLUMN_INDEX = {
    "license_plate": 0,
    "vehicle_type": 1,
    "brand": 2,
    "commercial_name": 3,
    "date_experitation_APK": 4,
    "date_ascription": 5,
    "brute_BPM": 6,
    "setup": 7,
    "number_of_seats": 8,
    "first_color": 9,
    "second_color": 10,
    "number_of_cilinders": 11,
    "cilinder_size": 12,
    "mass_empty": 13,
    "mass_max": 14,
    "mass_ready": 15,
    "maximum_mass_unbraked_pull": 16,
    "maximum_mass_braked_pull": 17,
    "retrofit_exhaust_filter": 18,
    "environmental_label": 19,
    "date_first_admission": 20,
    "date_first_admission_in_Netherlands": 21,
    "waiting_for_approval": 22,
    "catalog_prize": 23,
    "insured": 24,
    "number_of_doors": 25,
    "number_of_wheels": 26,
    "distance_clutch_to_rear_of_vehicle": 27,
    "distance_clutch_to_front_of_verhicle": 28,
    "length": 29,
    "width": 30,
    "location_of_chassisnumber": 31,
    "technical_maximum_mass_of_vehicle": 32,
    "type": 33,
    "type_gas_installation": 34,
    "type_approvalnumber": 35,
    "variant": 36,
    "specs": 37,
    "change_id_EU_type_approval": 38,
    "power_mass_ready_to_drive": 39,
    "wheelbase": 40,
    "exported": 41,
    "recall_indicator": 42
}
